### ISSUE TITLE
[Request] change movies, tv, music section icons

### ISSUE THREAD

**Issue by csjjpm** [plexinc/roku-client-public#303]
Hi,
  I changed the PNG files for 'section-movie.png' etc in the images folder and repackaged the zip but when I install it on my NowTV it still has the old icons.  Do I have to do something else to get the new ones to appear?
thanks
Paul

**Comment by sullman** [comment]
The library icons come from PMS, the packaged ones are only used as a fallback. There's a guide on the forums for how people have set up PMS to return custom library icons. If you'd rather hardcode it in the Roku client source code, take a look at https://github.com/plexinc/roku-client-public/blob/master/Plex/source/PlexContainer.brs#L83. You can probably just get rid of that `if` statement and always run that code that sets the library icons.

**Comment by csjjpm** [comment]
Hi Sullman,
  thanks for the feedback, I'll have a play with PMS
BW
Paul
