### ISSUE TITLE
Media Server Backwards Compatibility

### ISSUE THREAD

**Issue by joelpy** [plexinc/roku-client-public#306]
**Current State**

The current public release of the Plex Client for Roku - which was a mandatory upgrade - eliminated support for older Plex Media Servers prior to 0.9.11.1. This removed support for older hardware that has been repurposed as a media center, including all Mac Mini's prior to the Core 2 Duo hardware (i.e., one of the most popular media devices in the world).

![image](https://cloud.githubusercontent.com/assets/14045485/9569892/8b35ceb6-4f2e-11e5-9b56-80b924101094.png)

**Feature Request**

The request is to either:

a) Provide support for PMS version 0.9.8.6, or
b) Enable users to roll back to a prior version of the Plex client that supports 0.9.8.6

Thanks for your hard work - it looks awesome. Sadly until my Mac Mini is supported, I can't really enjoy it.

Thanks for your consideration,

Joel

**Comment by elan** [comment]
b) is already supported via the [Plex Classic](https://support.plex.tv/hc/en-us/articles/208016997-Why-are-there-both-Plex-and-Plex-Classic-channels-) channel. Hopefully that works for you :grinning:

**Comment by joelpy** [comment]
Touche. Yes, "B" worked, thanks for the link and the information.

Naturally, I'd still love "A" to be supported. I understand the newer Plex features aren't in the old PMS, but I don't see why the new client can't support the old PMS at least streaming.

**Comment by elan** [comment]
It would be missing lots of the endpoints around discovery, transcoder features, etc. Obviously possible, but it would be much harder in the client to account for all the differences.
