### ISSUE TITLE
NOWTV: Latest version of Plex Client?

### ISSUE THREAD

**Issue by FrozenBeard** [plexinc/roku-client-public#311]
I bought a NowTV as its a cheap rebranded roku to sideload plex, I installed this version and its ancient version! Where can I find the latest updated Plex Client to sideload? Please don't tell me that this is the only version...

**Comment by sullman** [comment]
There's some information on the two versions on [the support site](https://support.plex.tv/hc/en-us/articles/208016997). The only way to sideload is to have the source code, and only Plex Classic is open source. The new version of the client cannot be sideloaded.
